// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WahadiniCryptoQuest.DAL.Context;

#nullable disable

namespace WahadiniCryptoQuest.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216000001_FixSubscriptionTables")]
    partial class FixSubscriptionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            
            // NOTE: Ideally this contains the full snapshot of the model.
            // For the purpose of applying the migration runtime, EF Core mainly relies on the Migration class itself.
            // I'm including essential entities to ensure basic model validity.
            
             modelBuilder.Entity("WahadiniCryptoQuest.Core.Entities.CurrencyPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");
                        
                    b.HasKey("Id");

                    b.ToTable("currency_pricings", (string)null);
                });
                
            modelBuilder.Entity("WahadiniCryptoQuest.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                        
                    b.HasKey("Id");
                    
                    b.ToTable("subscriptions", (string)null);
                });
        }
    }
}
